# Copy to Nikeshh/Nikeshh/.github/workflows/snake.yml
# Enables: https://raw.githubusercontent.com/Nikeshh/Nikeshh/output/github-contribution-grid-snake-dark.svg

name: Generate contribution snake

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: Nikeshh
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
          clean: true
          single-commit: true
